---
 - name: Install pip
   apt: name=python-pip state=present

 - name: Stop a container
   docker_container:
     name: loginapp
     state: stopped

 - name: remove container
   docker_container:
     name: loginapp
     state: absent
     
 - name: Remove image
   docker_image:
     state: absent
     name: 192.168.56.102:5000/loginapp:latest
     tag: latest
     
 - name: pull an image
   docker_image:
     name: 192.168.56.102:5000/loginapp:latest
     source: pull

 - name: Running the container
   docker_container:
     image: 192.168.56.102:5000/loginapp:latest
     name: loginapp
     state: started
     published_ports:
        - "8080:8080"

 - name: Check if container is running
   shell: docker ps


