---
 - name: Install pip
   apt: name=python-pip state=present
   when: ansible_os_family == "Debian"

 - name: remove container
   docker_container:
     name: loginapp
     state: absent

 - name: pull an image
   docker_image:
     name: 192.168.1.10:5000/loginapp:{{BUILD_NUMBER}}
     source: pull

 - name: Running the container
   docker_container:
     image: 192.168.1.10:5000/loginapp:{{BUILD_NUMBER}}
     name: loginapp
     state: started
     published_ports:
        - "8080:8080"

 - name: Check if container is running
   shell: docker ps


