- hosts: appdeploy  
  gather_facts: false  
  sudo: true  
  tasks:    
  - name: Deploy App      
    copy: src=/var/lib/jenkins/jobs/workspace/loginwebapp/target/LoginWebApp.war dest="/var/lib/tomcat8/webapps/ LoginWebApp##{{ buildnum }}.war" owner=tomcat group=tomcat
